BoxLayout:
    orientation: 'vertical'
    Label:
        id: time
        text: '[b]00:00[/b]'
        font_name: './fonts/DSEG7Classic-Regular.ttf'
        font_size: 100
        markup: True

    BoxLayout:
        size_hint_y: 0.2
        Button:
            id: bt_start_stop
            text: 'Start'
            on_press: app.start_stop()

        Button:
            id: bt_reset
            text: 'Reset'
            on_press: app.reset()